# Generated by Django 3.2 on 2023-03-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formtesting', '0002_alter_session_session_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_description',
            field=models.TextField(blank=True, help_text='Session Description', max_length=2560, null=True),
        ),
    ]
