# Generated by Django 3.2 on 2023-03-01 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formtesting', '0002_auto_20230301_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formtesting.course'),
        ),
    ]
