# Generated by Django 3.2.6 on 2023-03-02 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formtesting', '0003_session_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='learningoutcome',
        ),
    ]
