# Generated by Django 3.2.6 on 2023-03-02 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formtesting', '0005_assignment_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='course',
        ),
    ]
