# Generated by Django 3.2.6 on 2023-03-04 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formtesting', '0006_remove_assignment_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='skill',
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learningoutcome', models.CharField(blank=True, help_text='Learning outcome', max_length=256, null=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formtesting.session')),
                ('skill', models.ManyToManyField(to='formtesting.Skill')),
            ],
            options={
                'db_table': 'LearningOutcome',
            },
        ),
    ]
