# Generated by Django 3.2.6 on 2023-03-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formtesting', '0008_auto_20230306_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningoutcome',
            name='skill',
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='skill',
            field=models.ManyToManyField(blank=True, null=True, to='formtesting.Skill', verbose_name='Skill'),
        ),
    ]
